# This file was generated by GoReleaser. DO NOT EDIT.
cask "certinfo" do
  name "certinfo"
  desc "CLI tool to analyze X.509 certificates and private keys"
  homepage "https://github.com/marco-introini/certinfo"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "certinfo"

  on_macos do
    on_intel do
      url "https://github.com/marco-introini/certinfo/releases/download/v#{version}/certinfo_Darwin_x86_64.tar.gz"
      sha256 "a571cbe677a6d5593a89cfed48037b5c21d5dfb466214c2139d2b4cc4729e3a8"
    end
    on_arm do
      url "https://github.com/marco-introini/certinfo/releases/download/v#{version}/certinfo_Darwin_arm64.tar.gz"
      sha256 "adab72586493c9d944cebe261fba2b466a11ccf2b6b91d727d76cc6167c34d9e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/marco-introini/certinfo/releases/download/v#{version}/certinfo_Linux_x86_64.tar.gz"
      sha256 "ebe2d003a29722b79bfee2eb47dab4336a483afb03f8bfba1fa36c915174b2bc"
    end
    on_arm do
      url "https://github.com/marco-introini/certinfo/releases/download/v#{version}/certinfo_Linux_arm64.tar.gz"
      sha256 "bcb25f70a4d78f7199454aa0556996bb8a09e5356b5d54216c399da6e6705306"
    end
  end

  # No zap stanza required
end
