# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certinfo < Formula
  desc "CLI tool to analyze X.509 certificates and private keys"
  homepage "https://github.com/marco-introini/certinfo"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marco-introini/certinfo/releases/download/v0.2.2/certinfo_Darwin_x86_64.tar.gz"
      sha256 "86af539bb3c4b15130c0addb0a520c6605034605c9a5b82cafe4dcdc839d7cee"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marco-introini/certinfo/releases/download/v0.2.2/certinfo_Darwin_arm64.tar.gz"
      sha256 "a3fe0a5194ae565aa8935fee7e350fb546cf37ccd1849dad1eace54a8fee53b3"

      def install
        bin.install "certinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-introini/certinfo/releases/download/v0.2.2/certinfo_Linux_x86_64.tar.gz"
      sha256 "f1b201dddce328c3b77ed43fab2cc5a02b8ab2086371cf1da6185000f66a66fc"
      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-introini/certinfo/releases/download/v0.2.2/certinfo_Linux_arm64.tar.gz"
      sha256 "d268a47a3d72dd2e73498a88a03beb0a8202f5d2c148480f7654d8f7051c5d27"
      def install
        bin.install "certinfo"
      end
    end
  end
end
