# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Certinfo < Formula
  desc "CLI tool to analyze X.509 certificates and private keys"
  homepage "https://github.com/marco-introini/certinfo"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marco-introini/certinfo/releases/download/v1.1.0/certinfo_Darwin_x86_64.tar.gz"
      sha256 "9d251ce789d48f6940929a3d6933d063418568f3efe62b2abe2ef86ba6c2835d"

      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marco-introini/certinfo/releases/download/v1.1.0/certinfo_Darwin_arm64.tar.gz"
      sha256 "d211fde0328b0b2525df8f1341ea090e4cf5a68bde3147628b22f76505364f05"

      def install
        bin.install "certinfo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-introini/certinfo/releases/download/v1.1.0/certinfo_Linux_x86_64.tar.gz"
      sha256 "535ed10d1920fbe16a9089f37f04f9d81ad93240b62f0753ab5cbbe491ad5b63"
      def install
        bin.install "certinfo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marco-introini/certinfo/releases/download/v1.1.0/certinfo_Linux_arm64.tar.gz"
      sha256 "783379eaa2ed7cd2b2201dd6f4b4cf59941387e4c4adfc26b5f1c03d86d2570f"
      def install
        bin.install "certinfo"
      end
    end
  end
end
